name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: DotNet Build
      run: dotnet build
    - name: DotNet Test
      run: dotnet test
    - name: NPM Install
      working-directory: DotnetTemplate.Web
      run: npm install  
    - name: NPM Build
      working-directory: DotnetTemplate.Web
      run: npm run build
    - name: NPM Test
      working-directory: DotnetTemplate.Web
      run: npm t
    - name: NPM Lint
      working-directory: DotnetTemplate.Web
      run: npm run lint